CREATE TABLE Students
(
	ROLL_NO INT PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	ADDRESS VARCHAR(100) NOT NULL,
	PHONE VARCHAR(10) NOT NULL,
	Age INT NOT NULL,
);

INSERT INTO Students (ROLL_NO, NAME, ADDRESS, PHONE, Age) VALUES
(1, 'HARSH', 'DELHI', 'XXXXXXXXXX', 18),
(2, 'PRATIK', 'BIHAR', 'XXXXXXXXXX', 19),
(3, 'RIYANKA', 'SILIGURI', 'XXXXXXXXXX', 20),
(4, 'DEEP', 'RAMNAGAR', 'XXXXXXXXXX', 18),
(5, 'SAPTARHI', 'KOLKATA', 'XXXXXXXXXX', 19),
(6, 'DHANRAJ', 'BARABAJAR', 'XXXXXXXXXX', 20),
(7, 'ROHIT', 'BALURGHAT', 'XXXXXXXXXX', 18),
(8, 'NIRAJ', 'ALIPUR', 'XXXXXXXXXX', 19);

SELECT * FROM Students;

CREATE TABLE StudentCourse
(
	COURSE_ID INT NOT NULL,
	ROLL_NO INT NOT NULL,
	PRIMARY KEY (COURSE_ID, ROLL_NO)
);

INSERT INTO StudentCourse(COURSE_ID, ROLL_NO) VALUES
(1, 1),
(2, 2),
(2, 3),
(3, 4),
(1, 5),
(4, 9),
(5, 10),
(4, 11);

SELECT * FROM StudentCourse;

SELECT s.ROLL_NO, s.NAME, s.ADDRESS, s.PHONE, s.Age, sc.COURSE_ID
FROM Students s
JOIN StudentCourse sc ON s.ROLL_NO = sc.ROLL_NO
ORDER BY ROLL_NO;


